triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/Trivia_Game_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between trivia game and trivia participant</description>
    <label>Trivia Game Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Salesforce Trivia Multiplayer Game: Score for the related game and related participant</description>
    <inlineHelpText>Score for the related game and related participant</inlineHelpText>
    <label>Score</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Participant__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia participant</description>
    <inlineHelpText>master-detail to trivia participant</inlineHelpText>
    <label>Trivia Participant</label>
    <referenceTo>Trivia_Participant__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/Trivia_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: trivia participant details</description>
    <label>Trivia Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: first name of the participant</description>
    <inlineHelpText>first name of the participant</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/Trivia_Participant_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: Junction object between trivia game participant and trivia game question</description>
    <label>Trivia Participant Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participant Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Time_to_Answer__c.field-meta.xml
<CustomField>
    <fullName>Time_to_Answer__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: time taken to answer the question in milliseconds</description>
    <inlineHelpText>time taken to answer the question in milliseconds</inlineHelpText>
    <label>Time to Answer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Trivia_Game_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Salesforce Trivia Multiplayer Game: lookup to Trivia Game Participant</description>
    <inlineHelpText>lookup to Trivia Game Participant</inlineHelpText>
    <label>Trivia Game Participant</label>
    <referenceTo>Trivia_Game_Participant__c</referenceTo>
    <relationshipLabel>Trivia Participant Questions</relationshipLabel>
    <relationshipName>Trivia_Participant_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

triviagame/force-app/main/default/classes/GameParticipantWrapper.cls
public class GameParticipantWrapper implements Comparable{
    @AuraEnabled
    public Trivia_Game_Participant__c getGameParticipant {get;set;}
    public GameParticipantWrapper(Trivia_Game_Participant__c gameParticipant){
        this.getGameParticipant = gameParticipant;
    }
    public Integer compareTo(Object obj){
        try{
            GameParticipantWrapper targetObj = (GameParticipantWrapper)obj;
            if (this.getGameParticipant.Score__c < targetObj.getGameParticipant.Score__c){
                return 1;
            }
            else if (this.getGameParticipant.Score__c > targetObj.getGameParticipant.Score__c){
                return -1;
            }
            else{
                List<Trivia_Participant_Question__c> participantQuestions = this.getGameParticipant.Trivia_Participant_Questions__r;
                List<Trivia_Participant_Question__c> participantQuestionsTarget = targetObj.getGameParticipant.Trivia_Participant_Questions__r;
                
                Integer totalTime = 0, totalTimeTarget = 0;
                if (participantQuestions != null && participantQuestions.size() > 0){
                    for (Trivia_Participant_Question__c question: participantQuestions){
                        totalTime += Integer.valueOf(question.Time_to_Answer__c);
                    }
                } 
                if (participantQuestionsTarget != null && participantQuestionsTarget.size() > 0){
                    for (Trivia_Participant_Question__c question: participantQuestionsTarget){
                        totalTimeTarget += Integer.valueOf(question.Time_to_Answer__c);
                    }
                }
                
                if (totalTime < totalTimeTarget){
                    return 1;
                }
                else if (totalTime > totalTimeTarget){
                    return -1;
                }
                else {
                    return this.getGameParticipant.Trivia_Participant__r.First_Name__c.compareTo(targetObj.getGameParticipant.Trivia_Participant__r.First_Name__c);
                }
            }
        }
        catch (Exception ex){
			system.debug(ex.getStackTraceString());
        }
        return 1;
    }
}