triviagame/force-app/main/default/objects/ParticipantActivity__e/ParticipantActivity__e.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: any events emitted due to participants joining the game/registering their details etc.</description>
    <label>ParticipantActivity</label>
    <pluralLabel>ParticipantActivity</pluralLabel>
</CustomObject>

triviagame/force-app/main/default/objects/ParticipantActivity__e/fields/GameId__c.field-meta.xml
<CustomField>
    <fullName>GameId__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: game identifier</description>
    <label>GameId</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivity__e/fields/MobileNumber__c.field-meta.xml
<CustomField>
    <fullName>MobileNumber__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: mobile number of the participant</description>
    <label>MobileNumber</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivity__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: event payload</description>
    <label>Payload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivity__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: type of the event</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivityEnhanced__e/ParticipantActivityEnhanced__e.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: these events will be published by ParticipantActivityMasterTrigger after enriching the payload and will be handled by EmpApi in TriviaGame lightning component</description>
    <label>ParticipantActivityEnhanced</label>
    <pluralLabel>ParticipantActivityEnhanced</pluralLabel>
</CustomObject>

triviagame/force-app/main/default/objects/ParticipantActivityEnhanced__e/fields/GameId__c.field-meta.xml
<CustomField>
    <fullName>GameId__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Game Identifier</description>
    <label>GameId</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivityEnhanced__e/fields/MobileNumber__c.field-meta.xml
<CustomField>
    <fullName>MobileNumber__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: MobileNumber of the participant</description>
    <label>MobileNumber</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivityEnhanced__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Even payload</description>
    <label>Payload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/ParticipantActivityEnhanced__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Type of event</description>
    <inlineHelpText>type of event</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game__c/Trivia_Game__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game</description>
    <label>Trivia Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game__c/fields/Game_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Game_Identifier__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Unique identifier amongst all the new, live or paused games.</description>
    <inlineHelpText>Unique identifier amongst all the new, live or paused games.</inlineHelpText>
    <label>Game Identifier</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Represents typical lifecycle of a trivia game</description>
    <inlineHelpText>Represents typical lifecycle of a trivia game</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/Trivia_Game_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between trivia game and trivia participant</description>
    <label>Trivia Game Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Game__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia game</description>
    <inlineHelpText>master-detail to trivia game</inlineHelpText>
    <label>Trivia Game</label>
    <referenceTo>Trivia_Game__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Participant__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia participant</description>
    <inlineHelpText>master-detail to trivia participant</inlineHelpText>
    <label>Trivia Participant</label>
    <referenceTo>Trivia_Participant__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/Trivia_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: trivia participant details</description>
    <label>Trivia Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: first name of the participant</description>
    <inlineHelpText>first name of the participant</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Is_Banned__c.field-meta.xml
<CustomField>
    <fullName>Is_Banned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce Trivia Multiplayer Game: check this to ban a participant</description>
    <inlineHelpText>check this to ban a participant</inlineHelpText>
    <label>Is Banned?</label>
    <type>Checkbox</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: last name of the participant</description>
    <inlineHelpText>Last name of the participant</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Mobile Number, could have been of type phone however, phone fields can not be set as unique so had to choose text as field type.</description>
    <externalId>true</externalId>
    <inlineHelpText>Mobile Number which was first used to register and participate for the game</inlineHelpText>
    <label>Mobile Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

triviagame/force-app/main/default/classes/ParticipantActivityTriggerHandler.cls
public class ParticipantActivityTriggerHandler {
    public void onAfterInsert(List<ParticipantActivity__e> newList){
        try{
            
            // list of request wrappers which will be used to talk to the participants through twilio
            List<InvalidGameIdNotifRequest> invalidGameIdNotifRequests = new List<InvalidGameIdNotifRequest>();
            List<UserRegisterNotifRequest> userRegisterNotifRequests = new List<UserRegisterNotifRequest>();
            List<MissingEnrollmentNotifRequest> missingEnrollmentNotifRequests = new List<MissingEnrollmentNotifRequest>();
            List<UserNameNotifRequest> usernameNotifRequests = new List<UserNameNotifRequest>();
            
            // list of platform events which will be consumed by empApi in UI
            List<ParticipantActivityEnhanced__e> enhancedEvents = new List<ParticipantActivityEnhanced__e>();
            
            // lists of entities which need to be added to the database
            List<Trivia_Participant__c> participantsToBeAdded = new List<Trivia_Participant__c>();
            List<Trivia_Game_Participant__c> gameParticipantsToBeAdded = new List<Trivia_Game_Participant__c>();
            
            // set of mobile numbers after parsing raw mobile numbers from platform event
            Set<String> mobileNumbers = new Set<String>();
            for (ParticipantActivity__e event: newList){
                mobileNumbers.add(ParticipantActivityTriggerHelper.parseMobileNumber(event.MobileNumber__c));
            }    
            
            // map of participant mobile number and gameParticipant record
            Map<String, Trivia_Game_Participant__c> gameParticipantMap = new Map<String, Trivia_Game_Participant__c>();
            List<Trivia_Game_Participant__c> gameParticipants = [Select Id, Trivia_Participant__r.Mobile_Number__c, Trivia_Game__r.Game_Identifier__c 
                                                                 from Trivia_Game_Participant__c where Trivia_Participant__r.Mobile_Number__c IN :mobileNumbers
                                                                 and Trivia_Game__r.Status__c in ('New', 'Live') Order by Createddate DESC];
            for (Trivia_Game_Participant__c gameParticipant : gameParticipants){
                gameParticipantMap.put(gameParticipant.Trivia_Participant__r.Mobile_Number__c, gameParticipant);
            }
            
            // map of participant mobile number and participant record
            Map<String, Trivia_Participant__c> participantMap = new Map<String, Trivia_Participant__c>();
            List<Trivia_Participant__c> participants = [Select Id, Mobile_Number__c, First_Name__c, Last_Name__c from Trivia_Participant__c 
                                                        where Mobile_Number__c IN :mobileNumbers
                                                        and Is_Banned__c != true Order by Createddate DESC];
            for (Trivia_Participant__c participant : participants){
                participantMap.put(participant.Mobile_Number__c, participant);
            }
            
            // set of gameIds which are either new or live
            Map<Integer, Trivia_Game__c> gameMap = new Map<Integer, Trivia_Game__c>();
            List<Trivia_Game__c> liveGames = [Select Id, Game_Identifier__c from Trivia_Game__c where Status__c in ('New', 'Live')];
            for (Trivia_Game__c game: liveGames){
                gameMap.put(Integer.valueOf(game.Game_Identifier__c), game);
            }
            
            for (ParticipantActivity__e event: newList){
                String mobileNumber = ParticipantActivityTriggerHelper.parseMobileNumber(event.MobileNumber__c);
                if (mobileNumber != null){
                    ParticipantActivityEnhanced__e enhancedEvent = new ParticipantActivityEnhanced__e();
                    enhancedEvent.MobileNumber__c = mobileNumber;
                    enhancedEvent.Type__c = event.Type__c;
                    enhancedEvent.Payload__c = event.Payload__c;
                    if (event.Type__c.equals('ANS_GAME')){
                    	if (gameParticipantMap.get(mobileNumber) != null){
                        	enhancedEvent.GameId__c = gameParticipantMap.get(mobileNumber).Trivia_Game__r.Game_Identifier__c;
                        }
                        else{
                            missingEnrollmentNotifRequests.add(new MissingEnrollmentNotifRequest(mobileNumber));
                        }
                    }
                    else if (event.Type__c.equals('JOIN_GAME')){
                        Integer gameId = Integer.valueOf(event.Payload__c.split(' ')[1].trim());
                        if (gameMap != null && gameMap.keySet().contains(gameId)){
                            enhancedEvent.GameId__c = Decimal.valueOf(gameId);
                            if (participantMap.get(mobileNumber) != null){
                                if (gameParticipantMap.get(mobileNumber) == null){
                                    gameParticipantsToBeAdded.add(new Trivia_Game_Participant__c(Trivia_Game__c = gameMap.get(gameId).Id, Trivia_Participant__c = participantMap.get(mobileNumber).Id));
                                }
                                else{
                                    continue;
                                }
                            }
                            else{
                                participantsToBeAdded.add(new Trivia_Participant__c(Mobile_Number__c = mobileNumber, First_Name__c = mobileNumber, Last_Name__c = ''));
                                Trivia_Participant__c participant = new Trivia_Participant__c(Mobile_Number__c = mobileNumber);
                                gameParticipantsToBeAdded.add(new Trivia_Game_Participant__c(Trivia_Game__c = gameMap.get(gameId).Id, Trivia_Participant__r = participant));
                                usernameNotifRequests.add(new UserNameNotifRequest(mobileNumber));
                            }
                        }
                        else{
                            invalidGameIdNotifRequests.add(new InvalidGameIdNotifRequest(gameId, mobileNumber));
                            continue;
                        }
                    }
                    else if (event.Type__c.equals('NAME')){
                        if (participantMap.get(mobileNumber) != null){
                            if (!String.isBlank(event.Payload__c)){
                                List<String> tokens = event.Payload__c.trim().split(' ');
                                if (tokens != null && tokens.size() > 0){
                                    participantMap.get(mobileNumber).First_Name__c = tokens[0].trim();
                                    if (tokens.size() == 2){
                                    	participantMap.get(mobileNumber).Last_Name__c = tokens[1].trim();
                                    }
                                    else if (tokens.size() > 2){
                                        participantMap.get(mobileNumber).First_Name__c = event.Payload__c.trim();
                                    }
                                } 
                            	userRegisterNotifRequests.add(new UserRegisterNotifRequest(mobileNumber));
                            }
                            enhancedEvent.GameId__c = gameParticipantMap.get(mobileNumber).Trivia_Game__r.Game_Identifier__c;
                        }  
                    }
                    enhancedEvents.add(enhancedEvent); 
                }
            }
            if (participantsToBeAdded.size() > 0){
                insert participantsToBeAdded;
            }
            if (gameParticipantsToBeAdded.size() > 0){
                insert gameParticipantsToBeAdded;
            }
            if (participantMap.values() != null && participantMap.values().size() > 0){
                update participantMap.values();
            }
            EventBus.publish(enhancedEvents);
            if (invalidGameIdNotifRequests.size() > 0){
            	ParticipantActivityTriggerHelper.notifyUserForInvalidGameId(invalidGameIdNotifRequests);
            }
            if (missingEnrollmentNotifRequests.size() > 0){
            	ParticipantActivityTriggerHelper.notifyUserForMissingEnrollment(missingEnrollmentNotifRequests);
            } 
            if (userRegisterNotifRequests.size() > 0){
            	ParticipantActivityTriggerHelper.notifyUserForRegistration(userRegisterNotifRequests);
            } 
            if (usernameNotifRequests.size() > 0){
            	ParticipantActivityTriggerHelper.notifyUserForUsername(usernameNotifRequests);
            } 
        }
        catch (Exception ex){
            system.debug(ex.getMessage());
            system.debug(ex.getStackTraceString());
        }
    }
}