triviagame/force-app/main/default/objects/Trivia_Game__c/Trivia_Game__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game</description>
    <label>Trivia Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/Trivia_Game_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between trivia game and trivia participant</description>
    <label>Trivia Game Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Game__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia game</description>
    <inlineHelpText>master-detail to trivia game</inlineHelpText>
    <label>Trivia Game</label>
    <referenceTo>Trivia_Game__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/Trivia_Game_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between Trivia Game and Trivia Question</description>
    <label>Trivia Game Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/fields/Trivia_Game__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia game</description>
    <inlineHelpText>master-detail to trivia game</inlineHelpText>
    <label>Trivia Game</label>
    <referenceTo>Trivia_Game__c</referenceTo>
    <relationshipLabel>Trivia Game Questions</relationshipLabel>
    <relationshipName>Trivia_Game_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/fields/Trivia_Question__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Question__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia question</description>
    <inlineHelpText>master-detail to trivia question</inlineHelpText>
    <label>Trivia Question</label>
    <referenceTo>Trivia_Question__c</referenceTo>
    <relationshipLabel>Trivia Game Questions</relationshipLabel>
    <relationshipName>Trivia_Game_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/Trivia_Participant_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: Junction object between trivia game participant and trivia game question</description>
    <label>Trivia Participant Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participant Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Answer_Chosen__c.field-meta.xml
<CustomField>
    <fullName>Answer_Chosen__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: answer chosen by the candidate if answered at all</description>
    <inlineHelpText>answer chosen by the candidate if answered at all</inlineHelpText>
    <label>Answer Chosen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Time_to_Answer__c.field-meta.xml
<CustomField>
    <fullName>Time_to_Answer__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: time taken to answer the question in milliseconds</description>
    <inlineHelpText>time taken to answer the question in milliseconds</inlineHelpText>
    <label>Time to Answer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Trivia_Game_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Salesforce Trivia Multiplayer Game: lookup to Trivia Game Participant</description>
    <inlineHelpText>lookup to Trivia Game Participant</inlineHelpText>
    <label>Trivia Game Participant</label>
    <referenceTo>Trivia_Game_Participant__c</referenceTo>
    <relationshipLabel>Trivia Participant Questions</relationshipLabel>
    <relationshipName>Trivia_Participant_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Trivia_Game_Question__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to Trivia Game Participant: lookup to trivia game question</description>
    <inlineHelpText>lookup to trivia game question</inlineHelpText>
    <label>Trivia Game Question</label>
    <referenceTo>Trivia_Game_Question__c</referenceTo>
    <relationshipLabel>Trivia Participant Questions</relationshipLabel>
    <relationshipName>Trivia_Participant_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/Trivia_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: a set of predefined questions to be used for trivia games</description>
    <label>Trivia Question</label>
    <nameField>
        <displayFormat>TQ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_A__c.field-meta.xml
<CustomField>
    <fullName>Choice_A__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option A</description>
    <inlineHelpText>Answer option A, is required</inlineHelpText>
    <label>Choice A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_B__c.field-meta.xml
<CustomField>
    <fullName>Choice_B__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option B</description>
    <inlineHelpText>Answer option B</inlineHelpText>
    <label>Choice B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_C__c.field-meta.xml
<CustomField>
    <fullName>Choice_C__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option C</description>
    <inlineHelpText>Answer option C</inlineHelpText>
    <label>Choice C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_D__c.field-meta.xml
<CustomField>
    <fullName>Choice_D__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option D</description>
    <inlineHelpText>Answer option D</inlineHelpText>
    <label>Choice D</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_E__c.field-meta.xml
<CustomField>
    <fullName>Choice_E__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option E</description>
    <inlineHelpText>Answer option E, optional field</inlineHelpText>
    <label>Choice E</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Correct_Answer_Option__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer_Option__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Correct Answer from multiple choices</description>
    <inlineHelpText>Correct Answer from multiple choices</inlineHelpText>
    <label>Correct Answer Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: question</description>
    <inlineHelpText>question</inlineHelpText>
    <label>Question</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

triviagame/force-app/main/default/classes/QuestionSummaryCtlr.cls
public class QuestionSummaryCtlr {
    public List<QuestionWrapper> questions {
        get {
            List<QuestionWrapper> questionWraps = new List<QuestionWrapper>();
            try{    
                Trivia_Game__c game = [select Id, (select Id, Trivia_Question__r.Question__c, Trivia_Question__r.Correct_Answer_Option__c, 
                                                   Trivia_Question__r.Choice_A__c, Trivia_Question__r.Choice_B__c, Trivia_Question__r.Choice_C__c, 
                                                   Trivia_Question__r.Choice_D__c, Trivia_Question__r.Choice_E__c from Trivia_Game_Questions__r) 
                                       from Trivia_Game__c where Id = :gameIds limit 1];
                Trivia_Game_Participant__c participant = [select Id, (select Id, Answer_Chosen__c, Trivia_Game_Question__c, 
                                                          Time_To_Answer__c from Trivia_Participant_Questions__r)
                                                          from Trivia_Game_Participant__c where id = :playerId limit 1];
                if (game != null){
                    
                    for (Trivia_Game_Question__c question: game.Trivia_Game_Questions__r){
                        QuestionWrapper questionWrap = new QuestionWrapper();
                        List<String> answers = new List<String>();
                        if (String.isNotBlank(question.Trivia_Question__r.Choice_A__c)){
                            answers.add('A. '+question.Trivia_Question__r.Choice_A__c);
                        }
                        if (String.isNotBlank(question.Trivia_Question__r.Choice_B__c)){
                            answers.add('B. '+question.Trivia_Question__r.Choice_B__c);
                        }
                        if (String.isNotBlank(question.Trivia_Question__r.Choice_C__c)){
                            answers.add('C. '+question.Trivia_Question__r.Choice_C__c);
                        }
                        if (String.isNotBlank(question.Trivia_Question__r.Choice_D__c)){
                            answers.add('D. '+question.Trivia_Question__r.Choice_D__c);
                        }
                        if (String.isNotBlank(question.Trivia_Question__r.Choice_E__c)){
                            answers.add('E. '+question.Trivia_Question__r.Choice_E__c);
                        }
                        questionWrap.answers = answers;
                        questionWrap.body = question.Trivia_Question__r.Question__c;
                        questionWrap.correctAnswer = question.Trivia_Question__r.Correct_Answer_Option__c;
                        questionWrap.playerAnswer = getPlayerAnswer(question.Id, participant);
                        
                        questionWraps.add(questionWrap);
                    }
                } 
                
            }
            catch (Exception ex){
                system.debug(ex.getStackTraceString());
            } 
            return questionWraps;
    	}
		set;
    }
    
    public String getPlayerAnswer(Id questionId, Trivia_Game_Participant__c participant){
        try{
        	if (String.isNotBlank(questionId) && participant != null && 
            participant.Trivia_Participant_Questions__r != null && participant.Trivia_Participant_Questions__r.size() > 0){
                for (Trivia_Participant_Question__c question: participant.Trivia_Participant_Questions__r){
                    if (question.Trivia_Game_Question__c == questionId){
                        return question.Answer_Chosen__c;
                    }
                }
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }    
        return '';
    }
    
    public Trivia_Game_Participant__c player{get;set;}
    public Id playerId{get;set;}
    public Id gameIds{get;set;}
    
    public class QuestionWrapper{
        public String body{get;set;}
        public List<String> answers{get;set;}
        public String playerAnswer{get;set;}
        public String correctAnswer{get;set;}
    }
}