triviagame/force-app/main/default/objects/Trivia_Game__c/Trivia_Game__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game</description>
    <label>Trivia Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Represents typical lifecycle of a trivia game</description>
    <inlineHelpText>Represents typical lifecycle of a trivia game</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/classes/TriviaGameTriggerHandler.cls
public class TriviaGameTriggerHandler {
	public void onAfterUpdate(List<Trivia_Game__c> newList, Map<Id, Trivia_Game__c> oldMap){
        try{
            Set<Id> endedGameIds = new Set<Id>();
            for (Trivia_Game__c game: newList){
                if (String.isNotBlank(game.status__c) && game.status__c.toUpperCase().equals('ENDED') && oldMap.get(game.Id).status__c != game.status__c){
                    endedGameIds.add(game.Id);
                }
            }
            if (endedGameIds.size() > 0){
                TriviaGameTriggerHelper.notifyParticipantsOnGameEnd(endedGameIds);
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
    }    
}