triviagame/force-app/main/default/objects/Trivia_Game__c/Trivia_Game__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game</description>
    <label>Trivia Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game__c/fields/Game_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Game_Identifier__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Unique identifier amongst all the new, live or paused games.</description>
    <inlineHelpText>Unique identifier amongst all the new, live or paused games.</inlineHelpText>
    <label>Game Identifier</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Represents typical lifecycle of a trivia game</description>
    <inlineHelpText>Represents typical lifecycle of a trivia game</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Config__mdt/Trivia_Game_Config__mdt.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game : configuration for trivia games</description>
    <label>Trivia Game Config</label>
    <pluralLabel>Trivia Game Configs</pluralLabel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Config__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: value of given configuration as indicated by name</description>
    <inlineHelpText>value of given configuration as indicated by name</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/Trivia_Game_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between trivia game and trivia participant</description>
    <label>Trivia Game Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Ranking amongst all the participants in the related game</description>
    <inlineHelpText>Ranking amongst all the participants in the related game</inlineHelpText>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Salesforce Trivia Multiplayer Game: Score for the related game and related participant</description>
    <inlineHelpText>Score for the related game and related participant</inlineHelpText>
    <label>Score</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Game__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia game</description>
    <inlineHelpText>master-detail to trivia game</inlineHelpText>
    <label>Trivia Game</label>
    <referenceTo>Trivia_Game__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Participant__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia participant</description>
    <inlineHelpText>master-detail to trivia participant</inlineHelpText>
    <label>Trivia Participant</label>
    <referenceTo>Trivia_Participant__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/Trivia_Game_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between Trivia Game and Trivia Question</description>
    <label>Trivia Game Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: The order in which questions appear on the screen during the game</description>
    <inlineHelpText>The order in which questions appear on the screen during the game</inlineHelpText>
    <label>Serial Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/fields/Trivia_Game__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia game</description>
    <inlineHelpText>master-detail to trivia game</inlineHelpText>
    <label>Trivia Game</label>
    <referenceTo>Trivia_Game__c</referenceTo>
    <relationshipLabel>Trivia Game Questions</relationshipLabel>
    <relationshipName>Trivia_Game_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Question__c/fields/Trivia_Question__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Question__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia question</description>
    <inlineHelpText>master-detail to trivia question</inlineHelpText>
    <label>Trivia Question</label>
    <referenceTo>Trivia_Question__c</referenceTo>
    <relationshipLabel>Trivia Game Questions</relationshipLabel>
    <relationshipName>Trivia_Game_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/Trivia_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: trivia participant details</description>
    <label>Trivia Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: first name of the participant</description>
    <inlineHelpText>first name of the participant</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: last name of the participant</description>
    <inlineHelpText>Last name of the participant</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Mobile Number, could have been of type phone however, phone fields can not be set as unique so had to choose text as field type.</description>
    <externalId>true</externalId>
    <inlineHelpText>Mobile Number which was first used to register and participate for the game</inlineHelpText>
    <label>Mobile Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/Trivia_Participant_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: Junction object between trivia game participant and trivia game question</description>
    <label>Trivia Participant Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participant Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Time_to_Answer__c.field-meta.xml
<CustomField>
    <fullName>Time_to_Answer__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: time taken to answer the question in milliseconds</description>
    <inlineHelpText>time taken to answer the question in milliseconds</inlineHelpText>
    <label>Time to Answer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Trivia_Game_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Salesforce Trivia Multiplayer Game: lookup to Trivia Game Participant</description>
    <inlineHelpText>lookup to Trivia Game Participant</inlineHelpText>
    <label>Trivia Game Participant</label>
    <referenceTo>Trivia_Game_Participant__c</referenceTo>
    <relationshipLabel>Trivia Participant Questions</relationshipLabel>
    <relationshipName>Trivia_Participant_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant_Question__c/fields/Trivia_Game_Question__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to Trivia Game Participant: lookup to trivia game question</description>
    <inlineHelpText>lookup to trivia game question</inlineHelpText>
    <label>Trivia Game Question</label>
    <referenceTo>Trivia_Game_Question__c</referenceTo>
    <relationshipLabel>Trivia Participant Questions</relationshipLabel>
    <relationshipName>Trivia_Participant_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/Trivia_Question__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: a set of predefined questions to be used for trivia games</description>
    <label>Trivia Question</label>
    <nameField>
        <displayFormat>TQ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trivia Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_A__c.field-meta.xml
<CustomField>
    <fullName>Choice_A__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option A</description>
    <inlineHelpText>Answer option A, is required</inlineHelpText>
    <label>Choice A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_B__c.field-meta.xml
<CustomField>
    <fullName>Choice_B__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option B</description>
    <inlineHelpText>Answer option B</inlineHelpText>
    <label>Choice B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_C__c.field-meta.xml
<CustomField>
    <fullName>Choice_C__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option C</description>
    <inlineHelpText>Answer option C</inlineHelpText>
    <label>Choice C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_D__c.field-meta.xml
<CustomField>
    <fullName>Choice_D__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option D</description>
    <inlineHelpText>Answer option D</inlineHelpText>
    <label>Choice D</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Choice_E__c.field-meta.xml
<CustomField>
    <fullName>Choice_E__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Answer option E</description>
    <inlineHelpText>Answer option E, optional field</inlineHelpText>
    <label>Choice E</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Correct_Answer_Option__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer_Option__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Correct Answer from multiple choices</description>
    <inlineHelpText>Correct Answer from multiple choices</inlineHelpText>
    <label>Correct Answer Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: question</description>
    <inlineHelpText>question</inlineHelpText>
    <label>Question</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

triviagame/force-app/main/default/classes/STMGPlaygroundCtlr.cls
public class STMGPlaygroundCtlr{
    @AuraEnabled
    public static Trivia_Game__c fetchGame(Integer gameId){
        try{
            List<Trivia_Game__c> game = [select Id, Status__c from Trivia_Game__c
                                         where Game_Identifier__c = :gameId limit 1];
            if (game != null && game.size() > 0){
                return game[0];
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
        return null;
    }
    
    @AuraEnabled
    public static Integer instantiateGame(){
        try{
            List<Trivia_Game__c> liveGames = [select Id, Status__c, Game_Identifier__c from Trivia_Game__c 
                                              where Status__c IN ('New', 'Live')  limit 1];
            Set<Integer> gameIds = new Set<Integer>();
            for (Trivia_Game__c liveGame: liveGames){
                gameIds.add(Integer.valueOf(liveGame.Game_Identifier__c));
            }
            Integer gameId = generateGameId();
            while (gameIds.contains(gameId) || gameId < 100000){
                gameId = generateGameId();
            }
            Trivia_Game__c game = new Trivia_Game__c();
            game.status__c = 'New';
            game.Game_Identifier__c = gameId;
            insert game;
            loadQuestionsOntoGame(game);
            return gameId;
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
    	return -1;
    }
    
    @AuraEnabled
    public static void loadQuestionsOntoGame(Trivia_Game__c game){
        try{
            List<Trivia_Question__c> allQuestions = [select Id, Question__c, Choice_A__c, Choice_B__c, Choice_C__c, 
                                                     Choice_D__c, Choice_E__c, Correct_Answer_Option__c from
                                                     Trivia_Question__c];
            List<Trivia_Game_Config__mdt> questionsPerGameConfig = [select Id, value__c from Trivia_Game_Config__mdt where developerName = 'QUESTIONS_PER_GAME' limit 1];
            if (questionsPerGameConfig != null && questionsPerGameConfig.size() > 0){
                Integer questionsPerGame = Integer.valueOf(questionsPerGameConfig[0].value__c);
                List<Trivia_Game_Question__c> gameQuestions = new List<Trivia_Game_Question__c>();
                for (Integer i = 0; i < questionsPerGame; i++){
                    Trivia_Game_Question__c gameQuestion = new Trivia_Game_Question__c();
                    gameQuestion.Trivia_Game__c = game.Id;
                    Integer randomIndex = generateRandomInteger(allQuestions.size());
                    gameQuestion.Trivia_Question__c = allQuestions.get(randomIndex).Id;
                    gameQuestion.Serial_Number__c = Decimal.valueOf(i+1);
                    allQuestions.remove(randomIndex);
                    gameQuestions.add(gameQuestion);
                }
                if (gameQuestions.size() > 0){
                    insert gameQuestions;
                }
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static List<Trivia_Game_Question__c> fetchGameQuestions(Integer gameId){
        try{
            Trivia_Game__c game = fetchGame(gameId);
            if (game != null){
                game.status__c = 'Live';
                update game;
            }
            List<Trivia_Game_Question__c> questions = [select Id, Trivia_Question__r.Question__c, 
                                                       Trivia_Question__r.Correct_Answer_Option__c, Trivia_Question__r.Choice_A__c,
                                                       Trivia_Question__r.Choice_B__c, Trivia_Question__r.Choice_C__c,
                                                       Trivia_Question__r.Choice_D__c, Trivia_Question__r.Choice_E__c from Trivia_Game_Question__c
                                                       where Trivia_Game__r.Game_Identifier__c = :gameId order by Serial_Number__c asc];
            return questions; 
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
        return null;
    }
    @AuraEnabled
    public static List<GameParticipantWrapper> fetchGameParticipants(Integer gameId){
        try{
            List<GameParticipantWrapper> participants = new List<GameParticipantWrapper>();
            
            List<Trivia_Game_Participant__c> players = [select Id, Trivia_Participant__r.First_Name__c, Trivia_Participant__r.Last_Name__c,
                                                        (select Id, Trivia_Game_Question__c, Time_to_Answer__c from Trivia_Participant_Questions__r), 
                                                        Score__c, Trivia_Participant__r.Mobile_Number__c, Ranking__c from Trivia_Game_Participant__c
                                                        where Trivia_Game__r.Game_Identifier__c = :gameId];
            for (Trivia_Game_Participant__c player: players){
                participants.add(new GameParticipantWrapper(player));
            }
            participants.sort();
            return participants;
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }  
        return null;
    }
    
    @AuraEnabled
    public static void processAnswer(Integer gameId, String player, String answer, Trivia_Game_Question__c question, Integer timeToAnswer){
        try{
            ParticipantWrapper participant = (ParticipantWrapper)JSON.deserialize(player, ParticipantWrapper.class);
            List<Trivia_Participant_Question__c> participantQuestions = [select Id from Trivia_Participant_Question__c where Trivia_Game_Participant__c = :participant.id
                                                                  and Trivia_Game_Question__c = :question.Id limit 1];
            if (participantQuestions == null || participantQuestions.size() == 0){
                Trivia_Participant_Question__c participantQuestion = new Trivia_Participant_Question__c();
                participantQuestion.Trivia_Game_Participant__c = participant.id;
                participantQuestion.Trivia_Game_Question__c = question.Id;
                participantQuestion.Answer_Chosen__c = answer;
                participantQuestion.Time_to_Answer__c = timeToAnswer;
                
                insert participantQuestion;
                if (answer.equals(question.Trivia_Question__r.Correct_Answer_Option__c)){
                    List<Trivia_Game_Participant__c> participants = [select Id, Score__c from Trivia_Game_Participant__c where id = :participant.id limit 1];
                    if (participants != null && participants.size() > 0){
                        participants[0].Score__c = participants[0].Score__c + 1;
                        update participants[0];
                    }
                }
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static void terminateGame(Integer gameId){
        try{
            Trivia_Game__c game = fetchGame(gameId);
            if (game != null){
                game.status__c = 'Ended';
                update game;
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static Integer generateGameId(){
        return Integer.valueOf(Math.random()*1000000);
    	
    }
    
    @AuraEnabled
    public static Integer generateRandomInteger(Integer n){
        return Integer.valueOf(Math.random()*n);
    }
    
    
    public class ParticipantWrapper{
        @AuraEnabled
        public Id id {get;set;}
        @AuraEnabled
        public Integer score{get;set;}
        @AuraEnabled
        public Integer ranking{get;set;}
    }
}