triviagame/force-app/main/default/objects/Trivia_Game__c/Trivia_Game__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game</description>
    <label>Trivia Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/Trivia_Game_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: junction object between trivia game and trivia participant</description>
    <label>Trivia Game Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Game Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Game__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Game__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia game</description>
    <inlineHelpText>master-detail to trivia game</inlineHelpText>
    <label>Trivia Game</label>
    <referenceTo>Trivia_Game__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Game_Participant__c/fields/Trivia_Participant__c.field-meta.xml
<CustomField>
    <fullName>Trivia_Participant__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: master-detail to trivia participant</description>
    <inlineHelpText>master-detail to trivia participant</inlineHelpText>
    <label>Trivia Participant</label>
    <referenceTo>Trivia_Participant__c</referenceTo>
    <relationshipLabel>Trivia Game Participants</relationshipLabel>
    <relationshipName>Trivia_Game_Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/Trivia_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: trivia participant details</description>
    <label>Trivia Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: email address of the participant</description>
    <inlineHelpText>Email address of the participant</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

triviagame/force-app/main/default/classes/TriviaGameTriggerHelper.cls
public class TriviaGameTriggerHelper {
    public static void notifyParticipantsOnGameEnd(Set<Id> gameIds){
        try{
            Map<Id, Trivia_Game_Participant__c> players = new Map<Id, Trivia_Game_Participant__c>([select Id, Trivia_Participant__r.Email_Address__c from Trivia_Game_Participant__c where Trivia_Game__c IN :gameIds and Trivia_Participant__r.Email_Address__c != null]);
            for (Trivia_Game_Participant__c player: players.values()){
                sendEmail(player);
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        } 
    }
    
    public static void sendEmail(Trivia_Game_Participant__c player){
        try{
            EmailTemplate et=[Select id from EmailTemplate where name = 'GameResultsNotification' limit 1];
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setToAddresses(new String[] {player.Trivia_Participant__r.email_address__c});
            message.setTemplateId(et.Id);
            message.setTargetObjectId([select id from contact limit 1].Id);
            message.setTreatTargetObjectAsRecipient(false);
            message.setWhatId(player.Id);
            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }    
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }     
    }
}