triviagame/force-app/main/default/objects/Trivia_Participant__c/Trivia_Participant__c.object-meta.xml
<CustomObject>
    <description>Salesforce Trivia Multiplayer Game: trivia participant details</description>
    <label>Trivia Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trivia Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Age of the participant</description>
    <inlineHelpText>Age of the participant</inlineHelpText>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: city of the participant</description>
    <inlineHelpText>city of the participant</inlineHelpText>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: country of the participant</description>
    <inlineHelpText>country of the participant</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: email address of the participant</description>
    <inlineHelpText>Email address of the participant</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: first name of the participant</description>
    <inlineHelpText>first name of the participant</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: last name of the participant</description>
    <inlineHelpText>Last name of the participant</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

triviagame/force-app/main/default/objects/Trivia_Participant__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Salesforce Trivia Multiplayer Game: Mobile Number, could have been of type phone however, phone fields can not be set as unique so had to choose text as field type.</description>
    <externalId>true</externalId>
    <inlineHelpText>Mobile Number which was first used to register and participate for the game</inlineHelpText>
    <label>Mobile Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

triviagame/force-app/main/default/classes/STMGRegisterParticipantCtlr.cls
public class STMGRegisterParticipantCtlr { 
    
    public STMGRegisterParticipantCtlr(){
    }    
    
    @RemoteAction
    public static Trivia_Participant__c getDetails(String mobileNumber){
        try{
            List<Trivia_Participant__c> participants = [select Id, First_Name__c, Last_Name__c, Mobile_Number__c,
                                                        Age__c, Email_Address__c, Country__c, City__c from Trivia_Participant__c 
                                                        where Mobile_Number__c = :mobileNumber limit 1];
            if (participants != null && participants.size() > 0){
                return participants[0];
            }
        }
        catch (Exception ex){
            system.debug(ex.getStackTraceString());
        }    
        return null;
    }    
    
    @RemoteAction
    public static ParticipantDetailResponse registerParticipant(String data){
        ParticipantDetailResponse resp = new ParticipantDetailResponse();
        resp.isSuccess = false;
        try{
            ParticipantDetailRequest req = (ParticipantDetailRequest)JSON.deserialize(data, ParticipantDetailRequest.class);
            
            
            Trivia_Participant__c participant = getDetails(req.mobileNumber);
            if (participant != null){
                participant = new Trivia_Participant__c(Id = participant.Id, First_Name__c= req.firstName, Last_Name__c= req.lastName, 
                                                        Email_Address__c= req.email, Age__c= req.age, Country__c = req.country, City__c = req.city);
                update participant;
            }
            else{
                participant = new Trivia_Participant__c(First_Name__c= req.firstName, Last_Name__c= req.lastName, 
                                                                Email_Address__c= req.email, Mobile_Number__c= req.mobileNumber, 
                                                                Age__c= req.age, Country__c = req.country, City__c = req.city);
                
            
            	insert participant;
            }    
            
            if (req.file != null){
                Blob fileData = EncodingUtil.base64Decode(req.file.split('base64,')[1].trim());
                List<String> fileNameParts = req.fileName.split('\\.');
                ContentVersion cv = new ContentVersion();
                cv.Title = 'ProfilePhoto';
                cv.PathOnClient = 'profilephoto.'+fileNameParts[fileNameParts.size()-1];
                cv.VersionData = fileData;
                cv.IsMajorVersion = true;
                Insert cv;
                
                Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
                
                ContentDocumentLink cdl = New ContentDocumentLink();
                cdl.LinkedEntityId = participant.Id;
                cdl.ContentDocumentId = conDocId;
                cdl.shareType = 'V';
                Insert cdl;
                
            }
            resp.isSuccess = true;
        }
        catch (Exception ex){
            ErrorDetail error = new ErrorDetail();
            error.messages = new List<String>{'Registration failed. Please contact Program Administrator!'};
            resp.error = error;
            system.debug(ex.getMessage());
            system.debug(ex.getStackTraceString());
        }
        return resp;
    }
    
    public class ParticipantDetailRequest{
        public String file { get; set; }
        public String fileName {get;set;}
        public String firstName {get;set;}
        public String lastName {get;set;}
        public String country {get;set;}
        public String city {get;set;}
        public String email {get; set;}
        public Integer age {get; set;}
        public String mobileNumber {get;set;}
    }
    
    public class ParticipantDetailResponse{
        public boolean isSuccess {get; set;}
        public ErrorDetail error {get; set;}
    }
    
    public class ErrorDetail{
        public List<String> messages {get; set;}
    }
}